name: developer-docs

static_sites:
- name: html
  environment_slug: html
  github:
    repo:  pagestudiocms/developers-docs 
    branch: new-master
    deploy_on_push: true
  source_dir: dist/html
  index_document: index.html
  routes:
  - path: /